export { default as ContactPage } from "./Contact";
export { default as HomePage } from "./Home";
export { default as IntroPage } from "./Intro";
export { default as LoginPage } from "./Login";
export { default as NewsPage } from "./News";
export { default as Page404 } from "./Page404";
export { default as Page500 } from "./Page500";
export { default as ProductPage } from "./Product";
export { default as RegisterPage } from "./Register";
