export { default as AboutPage } from "./About";
export { default as CheckoutPage } from "./Checkout";
export { default as ContactPage } from "./Contact";
export { default as HomePage } from "./Home";
export { default as LoginPage } from "./Login";
export { default as Page404 } from "./Page404";
export { default as Page500 } from "./Page500";
export { default as ProductPage } from "./Products";
export { default as RegisterPage } from "./Register";
